version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - setup_remote_docker: 
       docker_layer_caching: true
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

     # build the application image
     - run: docker build -t medayo/vsts-build-agent:$CIRCLE_BRANCH .
     # tag the application image
     - run: docker tag medayo/vsts-build-agent:$CIRCLE_BRANCH medayo/vsts-build-agent:latest

     # deploy the image
     - run: docker push medayo/vsts-build-agent:$CIRCLE_BRANCH
     - run: docker push medayo/vsts-build-agent:latest